# Generated by Django 6.0.5 on 2026-05-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
