# Generated by Django 6.0.5 on 2026-05-19 08:40

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='default_currency',
            field=models.CharField(blank=True, choices=[('USD', 'Dollar'), ('EUR', 'Euro'), ('GBP', 'GBP')], default='EUR', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('SARL', 'SARL'), ('SAS', 'SAS'), ('SASU', 'SASU'), ('EURL', 'EURL'), ('EI', 'EI')], default='SARL', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rcs_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='share_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='siren_siret_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
