# Generated by Django 6.0.5 on 2026-05-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_user_business_sector_user_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_country',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AL', 'Albanie'), ('DZ', 'Algérie'), ('AR', 'Argentine'), ('AU', 'Australie'), ('AT', 'Autriche'), ('BD', 'Bangladesh'), ('BE', 'Belgique'), ('BR', 'Brésil'), ('BG', 'Bulgarie'), ('CA', 'Canada'), ('CL', 'Chili'), ('CN', 'Chine'), ('CO', 'Colombie'), ('HR', 'Croatie'), ('CZ', 'République tchèque'), ('DK', 'Danemark'), ('EG', 'Égypte'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('FR', 'France'), ('DE', 'Allemagne'), ('GR', 'Grèce'), ('HK', 'Hong Kong'), ('HU', 'Hongrie'), ('IN', 'Inde'), ('ID', 'Indonésie'), ('IE', 'Irlande'), ('IL', 'Israël'), ('IT', 'Italie'), ('JP', 'Japon'), ('KE', 'Kenya'), ('LU', 'Luxembourg'), ('MY', 'Malaisie'), ('MX', 'Mexique'), ('MA', 'Maroc'), ('NL', 'Pays-Bas'), ('NZ', 'Nouvelle-Zélande'), ('NG', 'Nigeria'), ('NO', 'Norvège'), ('PK', 'Pakistan'), ('PE', 'Pérou'), ('PH', 'Philippines'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('QA', 'Qatar'), ('RO', 'Roumanie'), ('RU', 'Russie'), ('SA', 'Arabie saoudite'), ('SG', 'Singapour'), ('ZA', 'Afrique du Sud'), ('KR', 'Corée du Sud'), ('ES', 'Espagne'), ('SE', 'Suède'), ('CH', 'Suisse'), ('TW', 'Taïwan'), ('TH', 'Thaïlande'), ('TR', 'Turquie'), ('UA', 'Ukraine'), ('AE', 'Émirats arabes unis'), ('GB', 'Royaume-Uni'), ('US', 'États-Unis'), ('VN', 'Vietnam')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('AF', 'Afghanistan'), ('AL', 'Albanie'), ('DZ', 'Algérie'), ('AR', 'Argentine'), ('AU', 'Australie'), ('AT', 'Autriche'), ('BD', 'Bangladesh'), ('BE', 'Belgique'), ('BR', 'Brésil'), ('BG', 'Bulgarie'), ('CA', 'Canada'), ('CL', 'Chili'), ('CN', 'Chine'), ('CO', 'Colombie'), ('HR', 'Croatie'), ('CZ', 'République tchèque'), ('DK', 'Danemark'), ('EG', 'Égypte'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('FR', 'France'), ('DE', 'Allemagne'), ('GR', 'Grèce'), ('HK', 'Hong Kong'), ('HU', 'Hongrie'), ('IN', 'Inde'), ('ID', 'Indonésie'), ('IE', 'Irlande'), ('IL', 'Israël'), ('IT', 'Italie'), ('JP', 'Japon'), ('KE', 'Kenya'), ('LU', 'Luxembourg'), ('MY', 'Malaisie'), ('MX', 'Mexique'), ('MA', 'Maroc'), ('NL', 'Pays-Bas'), ('NZ', 'Nouvelle-Zélande'), ('NG', 'Nigeria'), ('NO', 'Norvège'), ('PK', 'Pakistan'), ('PE', 'Pérou'), ('PH', 'Philippines'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('QA', 'Qatar'), ('RO', 'Roumanie'), ('RU', 'Russie'), ('SA', 'Arabie saoudite'), ('SG', 'Singapour'), ('ZA', 'Afrique du Sud'), ('KR', 'Corée du Sud'), ('ES', 'Espagne'), ('SE', 'Suède'), ('CH', 'Suisse'), ('TW', 'Taïwan'), ('TH', 'Thaïlande'), ('TR', 'Turquie'), ('UA', 'Ukraine'), ('AE', 'Émirats arabes unis'), ('GB', 'Royaume-Uni'), ('US', 'États-Unis'), ('VN', 'Vietnam')], max_length=100),
        ),
    ]
