# Generated by Django 6.0.5 on 2026-05-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_user_company_country_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_country',
            field=models.CharField(blank=True, choices=[('Afghanistan', 'Afghanistan'), ('Albanie', 'Albanie'), ('Algérie', 'Algérie'), ('Argentine', 'Argentine'), ('Australie', 'Australie'), ('Autriche', 'Autriche'), ('Bangladesh', 'Bangladesh'), ('Belgique', 'Belgique'), ('Brésil', 'Brésil'), ('Bulgarie', 'Bulgarie'), ('Canada', 'Canada'), ('Chili', 'Chili'), ('Chine', 'Chine'), ('Colombie', 'Colombie'), ('Croatie', 'Croatie'), ('République tchèque', 'République tchèque'), ('Danemark', 'Danemark'), ('Égypte', 'Égypte'), ('Estonie', 'Estonie'), ('Finlande', 'Finlande'), ('France', 'France'), ('Allemagne', 'Allemagne'), ('Grèce', 'Grèce'), ('Hong Kong', 'Hong Kong'), ('Hongrie', 'Hongrie'), ('Inde', 'Inde'), ('Indonésie', 'Indonésie'), ('Irlande', 'Irlande'), ('Israël', 'Israël'), ('Italie', 'Italie'), ('Japon', 'Japon'), ('Kenya', 'Kenya'), ('Luxembourg', 'Luxembourg'), ('Malaisie', 'Malaisie'), ('Mexique', 'Mexique'), ('Maroc', 'Maroc'), ('Pays-Bas', 'Pays-Bas'), ('Nouvelle-Zélande', 'Nouvelle-Zélande'), ('Nigeria', 'Nigeria'), ('Norvège', 'Norvège'), ('Pakistan', 'Pakistan'), ('Pérou', 'Pérou'), ('Philippines', 'Philippines'), ('Pologne', 'Pologne'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('Roumanie', 'Roumanie'), ('Russie', 'Russie'), ('Arabie saoudite', 'Arabie saoudite'), ('Singapour', 'Singapour'), ('Afrique du Sud', 'Afrique du Sud'), ('Corée du Sud', 'Corée du Sud'), ('Espagne', 'Espagne'), ('Suède', 'Suède'), ('Suisse', 'Suisse'), ('Taïwan', 'Taïwan'), ('Thaïlande', 'Thaïlande'), ('Turquie', 'Turquie'), ('Ukraine', 'Ukraine'), ('Émirats arabes unis', 'Émirats arabes unis'), ('Royaume-Uni', 'Royaume-Uni'), ('États-Unis', 'États-Unis'), ('Vietnam', 'Vietnam')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Albanie', 'Albanie'), ('Algérie', 'Algérie'), ('Argentine', 'Argentine'), ('Australie', 'Australie'), ('Autriche', 'Autriche'), ('Bangladesh', 'Bangladesh'), ('Belgique', 'Belgique'), ('Brésil', 'Brésil'), ('Bulgarie', 'Bulgarie'), ('Canada', 'Canada'), ('Chili', 'Chili'), ('Chine', 'Chine'), ('Colombie', 'Colombie'), ('Croatie', 'Croatie'), ('République tchèque', 'République tchèque'), ('Danemark', 'Danemark'), ('Égypte', 'Égypte'), ('Estonie', 'Estonie'), ('Finlande', 'Finlande'), ('France', 'France'), ('Allemagne', 'Allemagne'), ('Grèce', 'Grèce'), ('Hong Kong', 'Hong Kong'), ('Hongrie', 'Hongrie'), ('Inde', 'Inde'), ('Indonésie', 'Indonésie'), ('Irlande', 'Irlande'), ('Israël', 'Israël'), ('Italie', 'Italie'), ('Japon', 'Japon'), ('Kenya', 'Kenya'), ('Luxembourg', 'Luxembourg'), ('Malaisie', 'Malaisie'), ('Mexique', 'Mexique'), ('Maroc', 'Maroc'), ('Pays-Bas', 'Pays-Bas'), ('Nouvelle-Zélande', 'Nouvelle-Zélande'), ('Nigeria', 'Nigeria'), ('Norvège', 'Norvège'), ('Pakistan', 'Pakistan'), ('Pérou', 'Pérou'), ('Philippines', 'Philippines'), ('Pologne', 'Pologne'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('Roumanie', 'Roumanie'), ('Russie', 'Russie'), ('Arabie saoudite', 'Arabie saoudite'), ('Singapour', 'Singapour'), ('Afrique du Sud', 'Afrique du Sud'), ('Corée du Sud', 'Corée du Sud'), ('Espagne', 'Espagne'), ('Suède', 'Suède'), ('Suisse', 'Suisse'), ('Taïwan', 'Taïwan'), ('Thaïlande', 'Thaïlande'), ('Turquie', 'Turquie'), ('Ukraine', 'Ukraine'), ('Émirats arabes unis', 'Émirats arabes unis'), ('Royaume-Uni', 'Royaume-Uni'), ('États-Unis', 'États-Unis'), ('Vietnam', 'Vietnam')], max_length=100),
        ),
    ]
