# Generated by Django 6.0.5 on 2026-05-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('paris', 'Paris'), ('lyon', 'Lyon'), ('marseille', 'Marseille'), ('bordeaux', 'Bordeaux'), ('toulouse', 'Toulouse')], max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(choices=[('france', 'France'), ('belgium', 'Belgique'), ('switzerland', 'Suisse'), ('luxembourg', 'Luxembourg')], max_length=100),
        ),
    ]
