# Generated by Django 6.0.5 on 2026-05-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0002_alter_client_city_alter_client_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('Paris', 'Paris'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Bordeaux', 'Bordeaux'), ('Toulouse', 'Toulouse')], max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_category',
            field=models.CharField(choices=[("Client dans l'UE (hors France)", "Client dans l'UE (hors France)"), ('Client hors UE', 'Client hors UE'), ('Client en France', 'Client en France')], max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('Indépendant', 'Indépendant'), ('Société', 'Société')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(choices=[('France', 'France'), ('Belgique', 'Belgique'), ('Suisse', 'Suisse'), ('Luxembourg', 'Luxembourg')], max_length=100),
        ),
    ]
