# Generated by Django 6.0.5 on 2026-05-16 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0003_alter_client_city_alter_client_client_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('Indépendant', 'Indépendant'), ('Société', 'Société')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('billing_address', models.TextField()),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(choices=[('Paris', 'Paris'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Bordeaux', 'Bordeaux'), ('Toulouse', 'Toulouse')], max_length=100)),
                ('country', models.CharField(choices=[('France', 'France'), ('Belgique', 'Belgique'), ('Suisse', 'Suisse'), ('Luxembourg', 'Luxembourg')], max_length=100)),
                ('client_category', models.CharField(choices=[("Client dans l'UE (hors France)", "Client dans l'UE (hors France)"), ('Client hors UE', 'Client hors UE'), ('Client en France', 'Client en France')], max_length=100)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('siren_siret', models.CharField(blank=True, max_length=100, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
