# Generated by Django 6.0.5 on 2026-05-16 03:39

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0004_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
