# Generated by Django 6.0.5 on 2026-05-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0005_alter_supplier_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(choices=[('France', 'France'), ('Belgique', 'Belgique'), ('Suisse', 'Suisse'), ('Luxembourg', 'Luxembourg')], max_length=100),
        ),
    ]
