# Generated by Django 6.0.5 on 2026-05-16 04:00

import Deshboard.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0007_alter_supplier_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=Deshboard.models.FrenchCountryField(max_length=2),
        ),
    ]
