# Generated by Django 6.0.5 on 2026-05-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0008_alter_supplier_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Virement bancaire', 'Virement bancaire'), ('Chèque', 'Chèque'), ('Carte de crédit', 'Carte de crédit'), ('Espèces', 'Espèces')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(choices=[('France', 'France'), ('Belgique', 'Belgique'), ('Suisse', 'Suisse'), ('Luxembourg', 'Luxembourg')], max_length=100),
        ),
    ]
