# Generated by Django 6.0.5 on 2026-05-16 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0009_supplier_payment_method_alter_supplier_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('accounting_number', models.PositiveIntegerField(null=True)),
                ('invoice_type', models.CharField(choices=[('vente', 'Vente'), ('achat', 'Achat')], max_length=20)),
                ('invoice_subtype', models.CharField(choices=[('facture', 'Facture'), ('avoir', 'Avoir')], default='facture', max_length=20)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('accounting_month', models.CharField(blank=True, max_length=7)),
                ('payment_method', models.CharField(blank=True, choices=[('virement_bancaire', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('carte_bancaire', 'Carte bancaire'), ('prelevement', 'Prélèvement automatique')], max_length=50)),
                ('payment_conditions', models.CharField(blank=True, choices=[('immediate', 'Immédiat'), ('15_jours', '15 jours'), ('30_jours', '30 jours'), ('45_jours', '45 jours'), ('60_jours', '60 jours')], max_length=50)),
                ('currency', models.CharField(choices=[('EUR', '€ Euro'), ('USD', '$ Dollar'), ('GBP', '£ Livre sterling')], default='EUR', max_length=10)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('a_traiter', 'À traiter'), ('traite', 'Traité'), ('verrouille', 'Verrouillé / Exporté')], default='brouillon', max_length=30)),
                ('client_category', models.CharField(blank=True, choices=[('france_b2b_b2c', 'France (B2B & B2C)'), ('eu_b2b', 'UE B2B'), ('eu_b2c', 'UE B2C'), ('non_eu', 'Hors UE')], max_length=50)),
                ('apply_tva', models.BooleanField(default=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accounting_account', models.CharField(blank=True, max_length=20)),
                ('is_frozen', models.BooleanField(default=False)),
                ('airtable_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='Deshboard.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs', to='Deshboard.invoice')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='Deshboard.supplier')),
            ],
            options={
                'ordering': ['-invoice_date', '-accounting_number'],
                'unique_together': {('company', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tva_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='Deshboard.invoice')),
            ],
        ),
    ]
