# Generated by Django 6.0.5 on 2026-05-17 08:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0010_invoice_invoiceline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
