# Generated by Django 6.0.5 on 2026-05-20 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0011_alter_invoiceline_tva_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('category', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('cash', 'Cash'), ('card', 'Card'), ('cheque', 'Cheque'), ('direct_debit', 'Direct debit'), ('other', 'Other')], max_length=50)),
                ('bank_account', models.CharField(choices=[('professional', 'Professional account'), ('personal', 'Personal account')], max_length=20)),
                ('bank_reference', models.CharField(blank=True, max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='bank_operations/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('reconciliation_status', models.CharField(choices=[('not_linked', 'Not linked'), ('partially_reconciled', 'Partially reconciled'), ('reconciled', 'Reconciled / Validated')], default='not_linked', max_length=30)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_operations', to='Deshboard.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
