
COUNTRY_TYPES = [
    ('Afghanistan', 'Afghanistan'),
    ('Albanie', 'Albanie'),
    ('Algérie', 'Algérie'),
    ('Argentine', 'Argentine'),
    ('Australie', 'Australie'),
    ('Autriche', 'Autriche'),
    ('Bangladesh', 'Bangladesh'),
    ('Belgique', 'Belgique'),
    ('Brésil', 'Brésil'),
    ('Bulgarie', 'Bulgarie'),
    ('Canada', 'Canada'),
    ('Chili', 'Chili'),
    ('Chine', 'Chine'),
    ('Colombie', 'Colombie'),
    ('Croatie', 'Croatie'),
    ('République tchèque', 'République tchèque'),
    ('Danemark', 'Danemark'),
    ('Égypte', 'Égypte'),
    ('Estonie', 'Estonie'),
    ('Finlande', 'Finlande'),
    ('France', 'France'),
    ('Allemagne', 'Allemagne'),
    ('Grèce', 'Grèce'),
    ('Hong Kong', 'Hong Kong'),
    ('Hongrie', 'Hongrie'),
    ('Inde', 'Inde'),
    ('Indonésie', 'Indonésie'),
    ('Irlande', 'Irlande'),
    ('Israël', 'Israël'),
    ('Italie', 'Italie'),
    ('Japon', 'Japon'),
    ('Kenya', 'Kenya'),
    ('Luxembourg', 'Luxembourg'),
    ('Malaisie', 'Malaisie'),
    ('Mexique', 'Mexique'),
    ('Maroc', 'Maroc'),
    ('Pays-Bas', 'Pays-Bas'),
    ('Nouvelle-Zélande', 'Nouvelle-Zélande'),
    ('Nigeria', 'Nigeria'),
    ('Norvège', 'Norvège'),
    ('Pakistan', 'Pakistan'),
    ('Pérou', 'Pérou'),
    ('Philippines', 'Philippines'),
    ('Pologne', 'Pologne'),
    ('Portugal', 'Portugal'),
    ('Qatar', 'Qatar'),
    ('Roumanie', 'Roumanie'),
    ('Russie', 'Russie'),
    ('Arabie saoudite', 'Arabie saoudite'),
    ('Singapour', 'Singapour'),
    ('Afrique du Sud', 'Afrique du Sud'),
    ('Corée du Sud', 'Corée du Sud'),
    ('Espagne', 'Espagne'),
    ('Suède', 'Suède'),
    ('Suisse', 'Suisse'),
    ('Taïwan', 'Taïwan'),
    ('Thaïlande', 'Thaïlande'),
    ('Turquie', 'Turquie'),
    ('Ukraine', 'Ukraine'),
    ('Émirats arabes unis', 'Émirats arabes unis'),
    ('Royaume-Uni', 'Royaume-Uni'),
    ('États-Unis', 'États-Unis'),
    ('Vietnam', 'Vietnam'),
]

